VectorND::Vector< T, N > Class Template Reference
2D vector class
#include <Vector.hpp>
Public Types
using iterator = T *
using const_iterator = const T *
Public Member Functions
Vector ()
Vector (const Vector &v)
Vector (const std::array< T, N > &data)
iterator begin () noexcept
const_iterator cbegin () const noexcept
iterator end () noexcept
const_iterator cend () const noexcept
template<typename U >
operator Vector< U, N > () const
Operator for the casting to one vector to another.
T & operator[] (size_t i)
element access operator (write)
T operator[] (size_t i) const
element access operator (read)
T at (size_t i) const
element access (read) with bounds checking
Vector operator+ (const Vector &otherVector) const
sum of 2 vectors and returns a new vector
Vector operator- (const Vector &otherVector) const
substraction
Vector operator- () const
unary minus operator
Vector & operator+= (const Vector &otherVector)
add a vector to the current vector
Vector & operator-= (const Vector &otherVector)
-= operator overloading
T dot (const Vector &otherVector) const
return dot product
Vector operator* (T scalar)
return result of multiplying a vector by a scalar
Vector operator* (const Vector &otherVector) const
element by element product
Vector operator/ (const Vector &otherVector) const
element by element division
Vector & operator*= (T scalar)
*= operator overlading. multiply by scalar
Vector & operator*= (const Vector &vector)
*= operator overlading. multiply by vector
Vector operator/ (T scalar)
return result of dividing a vector by a scalar
Vector & operator/= (T scalar)
/= operator overlading. divide by scalar
Vector & operator/= (const Vector &vector)
/= operator overlading. divide by vector
Vector mod (const Vector &otherVector) const
element by element remainder operation on each element
Vector mod (T scalar) const
apply the true modulo operation on each element
double norm () const
return the euclidean norm of a vector
double squaredNorm () const
return the absolute squared norm of a vector
double dist (const Vector &otherVector) const
return the euclidean distance between 2 vectors
double squaredDist (const Vector &otherVector) const
return the squared distance between 2 vectors
Vector periodicDiff (const Vector &otherVector, const Vector &domainSize) const
compute v1 - v2 (`vectorial distance` distance) with periodic boundaries
Vector reverse () const
reverse the order of the elements: {x,y} => {y,x}
bool operator== (const Vector &otherVector) const
equality operator
bool operator!= (const Vector &otherVector) const
inequality operator
Static Public Member Functions
static double norm (const Vector &vector)
return the euclidean norm of a vector (static function)
static double squaredNorm (const Vector &vector)
return the absolute squared norm of a vector (static function)
static double dist (const Vector &a, const Vector &b)
return the euclidean distance between 2 vectors a and b (static function)
static double squaredDist (const Vector &a, const Vector &b)
return the squared distance between 2 vectors a and b (static function)
Static Public Attributes
static constexpr size_t size = N
Friends
Vector operator* (T scalar, const Vector &vector)
return result of multiplying a scalar by a vecor
Vector operator/ (T scalar, const Vector &vector)
return result of dividing a scalar by a vecor
std::ostream & operator<< (std::ostream &os, const Vector &vector)
overload cout to print a vector
Detailed Description
template<typename T, size_t N>
class VectorND::Vector< T, N >
2D vector class
Template Parameters
T the type of the elements
N the number of elements
Definition at line 23 of file Vector.hpp.
Member Typedef Documentation
const_iterator
template<typename T , size_t N>
using VectorND::Vector< T, N >::const_iterator = const T*
Definition at line 30 of file Vector.hpp.
iterator
template<typename T , size_t N>
using VectorND::Vector< T, N >::iterator = T*
Definition at line 29 of file Vector.hpp.
Constructor & Destructor Documentation
Vector() [1/3]
template<typename T , size_t N>
VectorND::Vector< T, N >::Vector () [inline]
Definition at line 35 of file Vector.hpp.
: data{} {}
Vector() [2/3]
template<typename T , size_t N>
VectorND::Vector< T, N >::Vector (const Vector< T, N > & v) [inline]
Definition at line 37 of file Vector.hpp.
: data{v.data} {}
Vector() [3/3]
template<typename T , size_t N>
VectorND::Vector< T, N >::Vector (const std::array< T, N > & data) [inline]
Definition at line 39 of file Vector.hpp.
: data{data} {}
Member Function Documentation
at()
template<typename T , size_t N>
T VectorND::Vector< T, N >::at (size_t i) const [inline]
element access (read) with bounds checking
Parameters
i the index of the element
Definition at line 84 of file Vector.hpp.
                                {
        return data.at(i);
    }
begin()
template<typename T , size_t N>
iterator VectorND::Vector< T, N >::begin () [inline], [noexcept]
Definition at line 42 of file Vector.hpp.
{ return data.data(); }
cbegin()
template<typename T , size_t N>
const_iterator VectorND::Vector< T, N >::cbegin () const [inline], [noexcept]
Definition at line 43 of file Vector.hpp.
{ return data.data(); }
cend()
template<typename T , size_t N>
const_iterator VectorND::Vector< T, N >::cend () const [inline], [noexcept]
Definition at line 45 of file Vector.hpp.
{ return data.data() + N; }
dist() [1/2]
template<typename T , size_t N>
double VectorND::Vector< T, N >::dist (const Vector< T, N > & a, const Vector< T, N > & b) [static]
return the euclidean distance between 2 vectors a and b (static function)
Parameters
a
b
Returns
double
Definition at line 559 of file Vector.hpp.
                                                                      {
    return Vector<T, N>::norm(a - b);
}
References VectorND::Vector< T, N >::norm().
dist() [2/2]
template<typename T , size_t N>
double VectorND::Vector< T, N >::dist (const Vector< T, N > & otherVector) const
return the euclidean distance between 2 vectors
Parameters
otherVector
Returns
double
Definition at line 564 of file Vector.hpp.
                                                               {
    return Vector<T, N>::norm(*this - otherVector);
}
References VectorND::Vector< T, N >::norm().
dot()
template<typename T , size_t N>
T VectorND::Vector< T, N >::dot (const Vector< T, N > & otherVector) const
return dot product
Parameters
otherVector
Returns
Vector
Definition at line 432 of file Vector.hpp.
                                                         {
    T result{0};
    for (size_t i = 0; i < N; i++) {
        result += data[i] * otherVector.data[i];
    }
    return result;
}
end()
template<typename T , size_t N>
iterator VectorND::Vector< T, N >::end () [inline], [noexcept]
Definition at line 44 of file Vector.hpp.
{ return data.data() + N; }
mod() [1/2]
template<typename T , size_t N>
Vector< T, N > VectorND::Vector< T, N >::mod (const Vector< T, N > & otherVector) const
element by element remainder operation on each element
Parameters
otherVector
Returns
Vector
Definition at line 510 of file Vector.hpp.
                                                                    {
    Vector<T, N> result;
    for (size_t i = 0; i < N; i++) {
        // cast the to T
        result.data[i] = static_cast<T>(std::fmod(std::fmod(data[i], otherVector[i]) + otherVector[i], otherVector[i]));
    }
    return result;
}
mod() [2/2]
template<typename T , size_t N>
Vector< T, N > VectorND::Vector< T, N >::mod (T scalar) const
apply the true modulo operation on each element
Parameters
scalar
Returns
Vector
Definition at line 520 of file Vector.hpp.
                                             {
    Vector<T, N> result;
    for (size_t i = 0; i < N; i++) {
        result.data[i] = static_cast<T>(std::fmod(std::fmod(data[i], scalar) + scalar, scalar));
    }
    return result;
}
norm() [1/2]
template<typename T , size_t N>
double VectorND::Vector< T, N >::norm
return the euclidean norm of a vector
Parameters
vector
Returns
double
Definition at line 531 of file Vector.hpp.
                                {
    return std::sqrt(dot(*this));
}
Referenced by VectorND::Vector< T, N >::dist().
norm() [2/2]
template<typename T , size_t N>
double VectorND::Vector< T, N >::norm (const Vector< T, N > & vector) [static]
return the euclidean norm of a vector (static function)
Returns
double
Definition at line 538 of file Vector.hpp.
                                                    {
    return vector.norm();
}
References VectorND::Vector< T, N >::norm().
Referenced by VectorND::Vector< T, N >::norm().
operator Vector< U, N >()
template<typename T , size_t N>
template<typename U >
VectorND::Vector< T, N >::operator Vector< U, N > () const [inline]
Operator for the casting to one vector to another.
Definition at line 53 of file Vector.hpp.
                                  {
        Vector<U, N> result;
        for (size_t i = 0; i < N; ++i) {
            result[i] = static_cast<U>(data[i]);
        }
        return result;
    }
operator!=()
template<typename T , size_t N>
bool VectorND::Vector< T, N >::operator!= (const Vector< T, N > & otherVector) const [inline]
inequality operator
Parameters
otherVector
Returns
true if the vectors are not equal
false if the vectors are equal
Definition at line 613 of file Vector.hpp.
                                                                   {
    return !(*this == otherVector);
}
operator*() [1/2]
template<typename T , size_t N>
Vector< T, N > VectorND::Vector< T, N >::operator* (const Vector< T, N > & otherVector) const
element by element product
Parameters
otherVector
Returns
Vector
Definition at line 421 of file Vector.hpp.
                                                                          {
    Vector<T, N> result;
    for (size_t i = 0; i < N; i++) {
        result.data[i] = data[i] * otherVector.data[i];
    }
    return result;
}
operator*() [2/2]
template<typename T , size_t N>
Vector< T, N > VectorND::Vector< T, N >::operator* (T scalar)
return result of multiplying a vector by a scalar
Parameters
scalar
Returns
Vector
Definition at line 441 of file Vector.hpp.
                                             {
    Vector<T, N> result;
    for (size_t i = 0; i < N; i++) {
        result.data[i] = scalar * data[i];
    }
    return result;
}
operator*=() [1/2]
template<typename T , size_t N>
Vector< T, N > & VectorND::Vector< T, N >::operator*= (const Vector< T, N > & vector)
*= operator overlading. multiply by vector
Parameters
vector
Returns
Vector&
Definition at line 462 of file Vector.hpp.
                                                                      {
    for (size_t i = 0; i < N; i++) {
        data[i] *= otherVector.data[i];
    }
    return *this;
}
operator*=() [2/2]
template<typename T , size_t N>
Vector< T, N > & VectorND::Vector< T, N >::operator*= (T scalar)
*= operator overlading. multiply by scalar
Parameters
scalar
Returns
Vector&
Definition at line 452 of file Vector.hpp.
                                               {
    for (size_t i = 0; i < N; i++) {
        data[i] *= scalar;
    }
    return *this;
}
operator+()
template<typename T , size_t N>
Vector< T, N > VectorND::Vector< T, N >::operator+ (const Vector< T, N > & otherVector) const
sum of 2 vectors and returns a new vector
Parameters
otherVector
Returns
Vector
Definition at line 370 of file Vector.hpp.
                                                                          {
    Vector<T, N> result;
    for (size_t i = 0; i < N; i++) {
        result.data[i] = data[i] + otherVector.data[i];
    }
    return result;
}
operator+=()
template<typename T , size_t N>
Vector< T, N > & VectorND::Vector< T, N >::operator+= (const Vector< T, N > & otherVector)
add a vector to the current vector
Parameters
otherVector
Returns
Vector&
Definition at line 401 of file Vector.hpp.
                                                                      {
    for (size_t i = 0; i < N; i++) {
        data[i] += otherVector.data[i];
    }
    return *this;
}
operator-() [1/2]
template<typename T , size_t N>
Vector< T, N > VectorND::Vector< T, N >::operator-
unary minus operator
Returns
Vector
Definition at line 390 of file Vector.hpp.
                                           {
    Vector<T, N> result;
    for (size_t i = 0; i < N; i++) {
        result[i] = -data[i];
    }
    return result;
}
operator-() [2/2]
template<typename T , size_t N>
Vector< T, N > VectorND::Vector< T, N >::operator- (const Vector< T, N > & otherVector) const
substraction
Parameters
otherVector
Returns
Vector
Definition at line 381 of file Vector.hpp.
                                                                          {
    Vector<T, N> result;
    for (size_t i = 0; i < N; i++) {
        result.data[i] = data[i] - otherVector.data[i];
    }
    return result;
}
operator-=()
template<typename T , size_t N>
Vector< T, N > & VectorND::Vector< T, N >::operator-= (const Vector< T, N > & otherVector)
-= operator overloading
Parameters
otherVector
Returns
Vector&
Definition at line 411 of file Vector.hpp.
                                                                      {
    for (size_t i = 0; i < N; i++) {
        data[i] -= otherVector.data[i];
    }
    return *this;
}
operator/() [1/2]
template<typename T , size_t N>
Vector< T, N > VectorND::Vector< T, N >::operator/ (const Vector< T, N > & otherVector) const
element by element division
Parameters
otherVector
Returns
Vector
Definition at line 474 of file Vector.hpp.
                                                                          {
    Vector<T, N> result;
    for (size_t i = 0; i < N; i++) {
        result.data[i] = data[i] / otherVector.data[i];
    }
    return result;
}
operator/() [2/2]
template<typename T , size_t N>
Vector< T, N > VectorND::Vector< T, N >::operator/ (T scalar)
return result of dividing a vector by a scalar
Parameters
scalar
Returns
Vector
Definition at line 483 of file Vector.hpp.
                                             {
    Vector<T, N> result;
    for (size_t i = 0; i < N; i++) {
        result.data[i] = data[i] / scalar;
    }
    return result;
}
operator/=() [1/2]
template<typename T , size_t N>
Vector< T, N > & VectorND::Vector< T, N >::operator/= (const Vector< T, N > & vector)
/= operator overlading. divide by vector
Parameters
vector
Returns
Vector&
Definition at line 500 of file Vector.hpp.
                                                                      {
    for (size_t i = 0; i < N; i++) {
        data[i] /= otherVector.data[i];
    }
    return *this;
}
operator/=() [2/2]
template<typename T , size_t N>
Vector< T, N > & VectorND::Vector< T, N >::operator/= (T scalar)
/= operator overlading. divide by scalar
Parameters
scalar
Returns
Vector&
Definition at line 492 of file Vector.hpp.
                                               {
    for (size_t i = 0; i < N; i++) {
        data[i] /= scalar;
    }
    return *this;
}
operator==()
template<typename T , size_t N>
bool VectorND::Vector< T, N >::operator== (const Vector< T, N > & otherVector) const [inline]
equality operator
Parameters
otherVector
Returns
true if the vectors are equal
false if the vectors are not equal
Definition at line 606 of file Vector.hpp.
                                                                   {
    return data == otherVector.data;
}
operator[]() [1/2]
template<typename T , size_t N>
T& VectorND::Vector< T, N >::operator[] (size_t i) [inline]
element access operator (write)
Parameters
i the index of the element
Definition at line 66 of file Vector.hpp.
                                   {
        return data[i];
    }
operator[]() [2/2]
template<typename T , size_t N>
T VectorND::Vector< T, N >::operator[] (size_t i) const [inline]
element access operator (read)
Parameters
i the index of the element
Definition at line 75 of file Vector.hpp.
                                        {
        return data[i];
    }
periodicDiff()
template<typename T , size_t N>
Vector< T, N > VectorND::Vector< T, N >::periodicDiff (const Vector< T, N > & otherVector, const Vector< T, N > & domainSize) const
compute v1 - v2 (`vectorial distance` distance) with periodic boundaries
Parameters
otherVector
Returns
Vector
Definition at line 581 of file Vector.hpp.
                                                                                                             {
    // we compute the "true" difference with periodic boundaries
    auto diff = *this - otherVector;
    for (size_t i = 0; i < N; i++) {
        if (diff[i] > domainSize[i] / 2.) {
            diff[i] -= domainSize[i];
        } else if (diff[i] < -domainSize[i] / 2.) {
            diff[i] += domainSize[i];
        }
    }
    return diff;
}
reverse()
template<typename T , size_t N>
Vector< T, N > VectorND::Vector< T, N >::reverse
reverse the order of the elements: {x,y} => {y,x}
Returns
Vector
Definition at line 595 of file Vector.hpp.
                                         {
    Vector<T, N> result;
    for (size_t i = 0; i < N; i++) {
        result.data[i] = data[N - i - 1];
    }
    return result;
}
squaredDist() [1/2]
template<typename T , size_t N>
double VectorND::Vector< T, N >::squaredDist (const Vector< T, N > & a, const Vector< T, N > & b) [static]
return the squared distance between 2 vectors a and b (static function)
Parameters
a
b
Returns
double
Definition at line 571 of file Vector.hpp.
                                                                             {
    return Vector<T, N>::squaredNorm(a - b);
}
References VectorND::Vector< T, N >::squaredNorm().
squaredDist() [2/2]
template<typename T , size_t N>
double VectorND::Vector< T, N >::squaredDist (const Vector< T, N > & otherVector) const
return the squared distance between 2 vectors
Parameters
otherVector
Returns
double
Definition at line 576 of file Vector.hpp.
                                                                      {
    return Vector<T, N>::squaredNorm(*this - otherVector);
}
References VectorND::Vector< T, N >::squaredNorm().
squaredNorm() [1/2]
template<typename T , size_t N>
double VectorND::Vector< T, N >::squaredNorm
return the absolute squared norm of a vector
Returns
double
Definition at line 545 of file Vector.hpp.
                                       {
    return dot(*this);
}
Referenced by VectorND::Vector< T, N >::squaredDist().
squaredNorm() [2/2]
template<typename T , size_t N>
double VectorND::Vector< T, N >::squaredNorm (const Vector< T, N > & vector) [static]
return the absolute squared norm of a vector (static function)
Parameters
vector
Returns
double
Definition at line 552 of file Vector.hpp.
                                                           {
    return vector.squaredNorm();
}
References VectorND::Vector< T, N >::squaredNorm().
Referenced by VectorND::Vector< T, N >::squaredNorm().
Friends And Related Function Documentation
operator*
template<typename T , size_t N>
Vector operator* (T scalar, const Vector< T, N > & vector) [friend]
return result of multiplying a scalar by a vecor
Parameters
vector
scalar
Returns
Vector
Definition at line 150 of file Vector.hpp.
                                                            {
        Vector<T, N> result;
        for (size_t i = 0; i < N; i++) {
            result.data[i] = scalar * vector.data[i];
        }
        return result;
    }
operator/
template<typename T , size_t N>
Vector operator/ (T scalar, const Vector< T, N > & vector) [friend]
return result of dividing a scalar by a vecor
Parameters
vector
scalar
Returns
Vector
Definition at line 205 of file Vector.hpp.
                                                            {
            Vector<T, N> result;
        for (size_t i = 0; i < N; i++) {
            result.data[i] = scalar / vector.data[i];
        }
        return result;
    }
operator<<
template<typename T , size_t N>
std::ostream& operator<< (std::ostream & os, const Vector< T, N > & vector) [friend]
overload cout to print a vector
Parameters
os
vector
Returns
std::ostream&
Definition at line 351 of file Vector.hpp.
                                                                        {
        os << "[";
        for (size_t i = 0; i < N; i++) {
            os << vector.data[i];
            if (i < N - 1) {
                os << ", ";
            }
        }
        os << "]";
        return os;
    }
Member Data Documentation
size
template<typename T , size_t N>
constexpr size_t VectorND::Vector< T, N >::size = N [static], [constexpr]
Definition at line 33 of file Vector.hpp.
The documentation for this class was generated from the following file:
include/Vector.hpp